In [5]:
import numpy as np


- create
- basic operation
- math operation
- indexing and slicing
- boolean filter

In [6]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [10]:
z = [0,1,2,3,4,5,6,7,8,9]
nz = np.array([z]*10)
print(nz)
print(nz.shape)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
(10, 10)


- random
- arrange
- linspace

In [11]:
np.random.rand(3,3)

array([[0.70939917, 0.2995897 , 0.08059566],
       [0.78597057, 0.46087205, 0.39691511],
       [0.01199482, 0.24506251, 0.58614018]])

In [12]:
r1 = np.random.randint(-5,6, (5,5))
print(r1)

[[-5  2  3  4 -4]
 [-4 -3  0 -2  4]
 [-5  3 -3  2  1]
 [ 3 -1 -4  0  3]
 [-1  3 -4  3  0]]


In [13]:
#start, stop , gap
np.arange(0,50, .5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5,
       33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. ,
       38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5,
       44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. ,
       49.5])

In [14]:
#start, stop , number_of_items
np.linspace(0,50 , 100)

array([ 0.        ,  0.50505051,  1.01010101,  1.51515152,  2.02020202,
        2.52525253,  3.03030303,  3.53535354,  4.04040404,  4.54545455,
        5.05050505,  5.55555556,  6.06060606,  6.56565657,  7.07070707,
        7.57575758,  8.08080808,  8.58585859,  9.09090909,  9.5959596 ,
       10.1010101 , 10.60606061, 11.11111111, 11.61616162, 12.12121212,
       12.62626263, 13.13131313, 13.63636364, 14.14141414, 14.64646465,
       15.15151515, 15.65656566, 16.16161616, 16.66666667, 17.17171717,
       17.67676768, 18.18181818, 18.68686869, 19.19191919, 19.6969697 ,
       20.2020202 , 20.70707071, 21.21212121, 21.71717172, 22.22222222,
       22.72727273, 23.23232323, 23.73737374, 24.24242424, 24.74747475,
       25.25252525, 25.75757576, 26.26262626, 26.76767677, 27.27272727,
       27.77777778, 28.28282828, 28.78787879, 29.29292929, 29.7979798 ,
       30.3030303 , 30.80808081, 31.31313131, 31.81818182, 32.32323232,
       32.82828283, 33.33333333, 33.83838384, 34.34343434, 34.84

ARRAY ATTRIBUTES
 - shape
 - dtype
 - ndim
 - size

BASIC OPERATIONS
 - sum
 - mean
 - min
 - max
 - std
 - reshape
 - transpose
 - flatten

In [18]:
z = np.random.rand(3,3)
print(z.shape)
print(z.ndim)
print(z.dtype)
print(z.size)


(3, 3)
2
float64
9


In [20]:
a = np.random.rand(2,3)
print(a.sum())
print(a.sum(axis=0))  # coloumn- wise
print(a.sum(axis=1))  # Row-wise

print(a.mean())
print(a.max())
print(a.min())
print(a.std())
print(a.var())

4.575539065908567
[1.37435568 1.61165434 1.58952905]
[2.08485904 2.49068003]
0.7625898443180944
0.9874343869832296
0.4407947851927999
0.2071052611159636
0.04289258918191147


In [23]:
z = np.random.randint(11,99, (5,5))
print(z)
print('transpose')
print(z.transpose()) # or print(z.T)
print(z.flatten())


[[86 64 56 89 43]
 [29 41 39 81 59]
 [56 37 42 27 11]
 [51 68 58 73 64]
 [45 14 22 45 72]]
transpose
[[86 29 56 51 45]
 [64 41 37 68 14]
 [56 39 42 58 22]
 [89 81 27 73 45]
 [43 59 11 64 72]]
[86 64 56 89 43 29 41 39 81 59 56 37 42 27 11 51 68 58 73 64 45 14 22 45
 72]


In [25]:
a = np.random.randint(1,10,    (4,5))
print(a)
print(a.reshape(20))
print(a.reshape(4,5))
print(a.reshape(2,2,5))
print(a.reshape(2,5,2))


[[9 6 6 2 1]
 [4 5 5 3 4]
 [7 9 3 6 6]
 [9 1 1 7 7]]
[9 6 6 2 1 4 5 5 3 4 7 9 3 6 6 9 1 1 7 7]
[[9 6 6 2 1]
 [4 5 5 3 4]
 [7 9 3 6 6]
 [9 1 1 7 7]]
[[[9 6 6 2 1]
  [4 5 5 3 4]]

 [[7 9 3 6 6]
  [9 1 1 7 7]]]
[[[9 6]
  [6 2]
  [1 4]
  [5 5]
  [3 4]]

 [[7 9]
  [3 6]
  [6 9]
  [1 1]
  [7 7]]]


In [27]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,5],[4,6]])
print(a)
print(b)


[[1 2]
 [3 4]]
[[3 5]
 [4 6]]


array([[ 4,  7],
       [ 7, 10]])

In [ ]:
# When using 2 matrix, the shape must be the same
print(a+b)
print(a-b)
print(a/b)  # element wise division
print(a*b)  # element wise multiplication
print(a@b)  #matrix multiplication
print(a.dot(b)) #matrix multiplication

In [ ]:
# When using matrix and scalar
print(a-10) #broadcasting
print(a*10) #broadcasting
print(a/10) #broadcasting
print(a+10) #broadcasting


In [28]:
#Indexing
print(a[0,0])
print(a[-1,-1])


1
4


In [29]:
#Slicing

x = np.random.randint(1,10 , (5,5))
print(x)

[[3 4 5 5 4]
 [2 7 6 8 7]
 [8 1 1 7 3]
 [4 4 1 3 3]
 [8 2 3 8 6]]


SYNTAX 
 - array[rowstart:rowstop:rowgap, coloumnstart:coloumnstop:coloumngap]

In [32]:
x = np.random.randint(1,10 , (5,5))
print(x)
print('- first coloumn')
print(x[:,0])  # first coloumn
print('- last coloumn')
print(x[:,-1]) # last coloumn
print('- first three coloumn')
print(x[:,:3]) #first 3 coloumn

[[2 7 4 8 5]
 [7 8 2 7 5]
 [5 6 2 6 2]
 [6 9 1 6 3]
 [3 1 5 1 6]]
- first coloumn
[2 7 5 6 3]
- last coloumn
[5 5 2 3 6]
- first three coloumn
[[2 7 4]
 [7 8 2]
 [5 6 2]
 [6 9 1]
 [3 1 5]]
